-- +goose Up
CREATE TABLE ordered_products(
        ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_code UUID NOT NULL,
        User_UUID UUID NOT NULL,
        product_code INT NOT NULL,
        amount INT NOT NULL);
-- +goose Down
DROP TABLE ordered_products;
