-- +goose Up
CREATE TABLE cart(
        ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        User_UUID UUID NOT NULL,
        product_code INT NOT NULL,
        amount INT NOT NULL);
-- +goose Down
DROP TABLE cart;
